on: [push, pull_request]
name: Run test suite
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download swaggo
      run: go install github.com/swaggo/swag/cmd/swag@latest
    - name: Install swaggo
      run: swag init -d adapter/http --parseDependency --parseInternal --parseDepth 2 -o adapter/http/docs
    - name: Test
      run: go mod tidy && go test ./... -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage report
      uses: codecov/codecov-action@v3.1.1
      with:
        token: 1a4b3441-a035-466f-ba5e-f9242c2ef121
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella